[package]
name = "rgpt-types"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
serde = { version = "1.0.209", features = ["derive"] }
tokio-stream = { version = "0.1.0", features = ["full"] }
pin-project-lite = "0.2.14"
